### ISSUE TITLE
loading spreadsheet (optional)

### ISSUE THREAD

**Issue by podhmo** [podhmo/dictknife#42]
loading creadentials for defact gpc's cli?

**Comment by podhmo** [comment]
https://cloud.google.com/sdk/docs/initializing

**Comment by podhmo** [comment]
loading ini is needed?

**Comment by podhmo** [comment]
gcloud stores credentials at $HOME/.gcloud/credentials.db (sqite3).

**Comment by podhmo** [comment]
todo: credentials information (profile)

**Comment by podhmo** [comment]
todo: guess format from https://docs.google.com/spreadsheets/d/xXXxxXXXXxxXXxXXxXXXXxXXxxxXXxXxxxxxXxxxxXXx/edit#gid=1386834576

**Comment by podhmo** [comment]
supress warning

```
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "$HOME/venv/gcp/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/venv/gcp/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/venv/gcp/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/venv/gcp/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "$HOME/venv/gcp/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
```

**Comment by podhmo** [comment]
```
$ dictknife cat -i spreadsheet '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms#/Class Data!A1:E'  -o json
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/values/Class%20Data%21A1%3AE?alt=json
[
  {
    "Student Name": "Alexandra",
    "Gender": "Female",
    "Class Level": "4. Senior",
    "Home State": "CA",
    "Major": "English"
  },
  {
    "Student Name": "Andrew",
    "Gender": "Male",
    "Class Level": "1. Freshman",
    "Home State": "SD",
    "Major": "Math"
  },
  {
    "Student Name": "Anna",
    "Gender": "Female",
    "Class Level": "1. Freshman",
    "Home State": "NC",
    "Major": "English"
  },
  {
    "Student Name": "Becky",
    "Gender": "Female",
    "Class Level": "2. Sophomore",
    "Home State": "SD",
    "Major": "Art"
  },
  {
    "Student Name": "Benjamin",
    "Gender": "Male",
    "Class Level": "4. Senior",
    "Home State": "WI",
    "Major": "English"
  },
  {
    "Student Name": "Carl",
    "Gender": "Male",
    "Class Level": "3. Junior",
    "Home State": "MD",
    "Major": "Art"
  },
  {
    "Student Name": "Carrie",
    "Gender": "Female",
    "Class Level": "3. Junior",
    "Home State": "NE",
    "Major": "English"
  },
  {
    "Student Name": "Dorothy",
    "Gender": "Female",
    "Class Level": "4. Senior",
    "Home State": "MD",
    "Major": "Math"
  },
  {
    "Student Name": "Dylan",
    "Gender": "Male",
    "Class Level": "1. Freshman",
    "Home State": "MA",
    "Major": "Math"
  },
  {
    "Student Name": "Edward",
    "Gender": "Male",
    "Class Level": "3. Junior",
    "Home State": "FL",
    "Major": "English"
  },
  {
    "Student Name": "Ellen",
    "Gender": "Female",
    "Class Level": "1. Freshman",
    "Home State": "WI",
    "Major": "Physics"
  },
  {
    "Student Name": "Fiona",
    "Gender": "Female",
    "Class Level": "1. Freshman",
    "Home State": "MA",
    "Major": "Art"
  },
  {
    "Student Name": "John",
    "Gender": "Male",
    "Class Level": "3. Junior",
    "Home State": "CA",
    "Major": "Physics"
  },
  {
    "Student Name": "Jonathan",
    "Gender": "Male",
    "Class Level": "2. Sophomore",
    "Home State": "SC",
    "Major": "Math"
  },
  {
    "Student Name": "Joseph",
    "Gender": "Male",
    "Class Level": "1. Freshman",
    "Home State": "AK",
    "Major": "English"
  },
  {
    "Student Name": "Josephine",
    "Gender": "Female",
    "Class Level": "1. Freshman",
    "Home State": "NY",
    "Major": "Math"
  },
  {
    "Student Name": "Karen",
    "Gender": "Female",
    "Class Level": "2. Sophomore",
    "Home State": "NH",
    "Major": "English"
  },
  {
    "Student Name": "Kevin",
    "Gender": "Male",
    "Class Level": "2. Sophomore",
    "Home State": "NE",
    "Major": "Physics"
  },
  {
    "Student Name": "Lisa",
    "Gender": "Female",
    "Class Level": "3. Junior",
    "Home State": "SC",
    "Major": "Art"
  },
  {
    "Student Name": "Mary",
    "Gender": "Female",
    "Class Level": "2. Sophomore",
    "Home State": "AK",
    "Major": "Physics"
  },
  {
    "Student Name": "Maureen",
    "Gender": "Female",
    "Class Level": "1. Freshman",
    "Home State": "CA",
    "Major": "Physics"
  },
  {
    "Student Name": "Nick",
    "Gender": "Male",
    "Class Level": "4. Senior",
    "Home State": "NY",
    "Major": "Art"
  },
  {
    "Student Name": "Olivia",
    "Gender": "Female",
    "Class Level": "4. Senior",
    "Home State": "NC",
    "Major": "Physics"
  },
  {
    "Student Name": "Pamela",
    "Gender": "Female",
    "Class Level": "3. Junior",
    "Home State": "RI",
    "Major": "Math"
  },
  {
    "Student Name": "Patrick",
    "Gender": "Male",
    "Class Level": "1. Freshman",
    "Home State": "NY",
    "Major": "Art"
  },
  {
    "Student Name": "Robert",
    "Gender": "Male",
    "Class Level": "1. Freshman",
    "Home State": "CA",
    "Major": "English"
  },
  {
    "Student Name": "Sean",
    "Gender": "Male",
    "Class Level": "1. Freshman",
    "Home State": "NH",
    "Major": "Physics"
  },
  {
    "Student Name": "Stacy",
    "Gender": "Female",
    "Class Level": "1. Freshman",
    "Home State": "NY",
    "Major": "Math"
  },
  {
    "Student Name": "Thomas",
    "Gender": "Male",
    "Class Level": "2. Sophomore",
    "Home State": "RI",
    "Major": "Art"
  },
  {
    "Student Name": "Will",
    "Gender": "Male",
    "Class Level": "4. Senior",
    "Home State": "FL",
    "Major": "Math"
  }
]
```

**Comment by podhmo** [comment]
tentative

**Comment by podhmo** [comment]
pip install -e [spreadsheet]
